### ISSUE TITLE
App crashes after clicking the Reference icon

### ISSUE THREAD

**Issue by silvzr** [Iamlooker/Kenko#5]
![Screenshot_20240515-104107_Kenko.png](https://github.com/Iamlooker/Kenko/assets/117378129/442b6905-daad-4696-9add-e8518627c2d4)

if you click the Reference icon from this section, the app crashes resulting in this error 

FATAL EXCEPTION: main
Process: com.looker.kenko, PID: 31190
java.lang.IllegalArgumentException: Can't open .
	at A.p.f(Unknown Source:103)
	at n.s.n(Unknown Source:1505)
	at q.L0.r(Unknown Source:132)
	at i3.a.t(Unknown Source:8)
	at A3.C.v(Unknown Source:78)
	at A3.g.r(Unknown Source:104)
	at A3.g.F(Unknown Source:32)
	at A3.g.t(Unknown Source:16)
	at q0.D.W0(Unknown Source:50)
	at q0.D.u0(Unknown Source:31)
	at n.x.u0(Unknown Source:116)
	at q0.g.f(Unknown Source:156)
	at q0.g.f(Unknown Source:135)
	at q0.g.f(Unknown Source:135)
	at q0.g.f(Unknown Source:135)
	at q0.g.f(Unknown Source:135)
	at q0.g.f(Unknown Source:135)
	at A.B0.h(Unknown Source:35)
	at J.E.c(Unknown Source:137)
	at x0.t.F(Unknown Source:80)
	at x0.t.n(Unknown Source:374)
	at x0.t.dispatchTouchEvent(Unknown Source:75)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:500)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1912)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4307)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:458)
	at android.view.View.dispatchPointerEvent(View.java:15309)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6782)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6578)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6034)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6091)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6057)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6222)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6065)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6279)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6038)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6091)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6057)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6065)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6038)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9218)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9169)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9138)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9341)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:267)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loopOnce(Looper.java:161)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7956)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:962)
	Suppressed: F3.g: [x0.A0@b20834e, N.g@12ddc6f, F{Cancelling}@68add7c, W@2844605]
Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat= }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2214)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1848)
	at android.app.Activity.startActivityForResult(Activity.java:5554)
	at b.l.startActivityForResult(SourceFile:2)
	at android.app.Activity.startActivityForResult(Activity.java:5473)
	at b.l.startActivityForResult(SourceFile:1)
	at android.app.Activity.startActivity(Activity.java:6010)
	at android.app.Activity.startActivity(Activity.java:5977)
	at A.p.f(Unknown Source:77)
	... 60 more

**Comment by Iamlooker** [comment]
Thats because the reference is `.`

But will fix it in next release
